include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code style & consistency
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    depend_on_referenced_packages: true

    # Readability
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # Best practices
    avoid_print: true
    use_key_in_widget_constructors: true
    avoid_field_initializers_in_const_classes: true
    avoid_positional_boolean_parameters: true

    # Flutter-specific
    require_trailing_commas: true
    prefer_const_constructors_in_immutables: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
