name: test_telegram_modal_animation
description: A Flutter project demonstrating draggable modal with WebView.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-267.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true


  assets:
    - assets/splash_logo.png



flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png
  android_12:
    image: assets/splash_logo.png
    icon_background_color: "#FFFFFF"

